from __future__ import annotations

from typing import Any


EDITOR_CAPABILITY_SCHEMA_VERSION = 1


def editor_capability_manifest() -> dict[str, Any]:
    """Return the desktop/headless editor feature surface for agent audits."""
    return {
        "schema_version": EDITOR_CAPABILITY_SCHEMA_VERSION,
        "status": "authoring-only",
        "target": "TJC8048X543_011C",
        "feature_groups": [
            {
                "id": "project_pages",
                "status": "implemented",
                "features": [
                    "new scene",
                    "save as",
                    "project metadata edit",
                    "canvas width/height/background edit",
                    "page add/duplicate/delete",
                    "page id/layout edit",
                    "selected page preview",
                ],
                "entrypoints": [
                    "desktop New/Save As/Project/Page/Preview Page",
                    "scene new",
                    "scene save-as",
                    "scene project update",
                    "scene pages add/duplicate/update/delete",
                    "scene agent-preview --page",
                ],
            },
            {
                "id": "widget_authoring",
                "status": "implemented",
                "features": [
                    "toolbox template loading",
                    "widget add/copy/cut/paste/duplicate/delete",
                    "basic property edit",
                    "widget rename event-reference warnings",
                    "optional widget rename event-reference rewrite",
                    "style/resources/bindings JSON edit",
                    "object z-order up/down/front/back",
                    "object-tree and canvas shortcuts for copy/cut/paste/duplicate/delete",
                    "scene-file undo/redo for GUI edits",
                ],
                "entrypoints": [
                    "desktop Toolbox/Properties/Object tree",
                    "widgets template",
                    "scene widgets update/copy/cut/paste/copy-to/duplicate/delete/move",
                ],
            },
            {
                "id": "canvas_layout",
                "status": "implemented",
                "features": [
                    "click select",
                    "drag move",
                    "bottom-right resize",
                    "arrow-key nudge",
                    "configurable snap grid",
                    "multi-select align",
                    "multi-select distribute",
                    "multi-select same width/height/size",
                    "undo/redo for scene geometry edits",
                    "agent patch replay",
                ],
                "entrypoints": [
                    "desktop preview canvas",
                    "scene design move/resize/align/distribute/match-size/replay",
                ],
            },
            {
                "id": "events",
                "status": "guarded-subset",
                "features": [
                    "event list/get/set/clear",
                    "event snippets",
                    "structured event command append",
                    "event command list/insert/replace/delete/move",
                    "event command diff/dry-run and optional before/after simulation",
                    "desktop event line move/delete helpers",
                    "event lint",
                    "navigation graph",
                    "offline event simulation",
                    "offline trigger/assert scenario runner",
                ],
                "entrypoints": [
                    "desktop Events tab",
                    "scene events list/get/set/append-command/commands/clear/lint/graph/snippets",
                    "scene simulate",
                    "scene scenario run",
                    "scene check --simulate-events --scenario",
                ],
            },
            {
                "id": "assets_import_export",
                "status": "implemented",
                "features": [
                    "scene asset add/update/delete",
                    "lossy HMI import",
                    "preview bundle",
                    "offline scene check",
                    "offline export bundle",
                    "explicit TFT build button",
                ],
                "entrypoints": [
                    "desktop Assets/Import HMI/Roundtrip HMI/Preview Bundle/Check Scene/Export Bundle/Build TFT",
                    "hmi import",
                    "scene agent-preview",
                    "scene check",
                    "scene export",
                    "scene build",
                ],
            },
        ],
        "hardware_policy": {
            "implicit_upload": False,
            "upload_entrypoint": "tft upload",
            "default_port": "COM36",
            "requires_explicit_user_request": True,
        },
        "not_claimed": [
            "byte-perfect official USART HMI project roundtrip",
            "complete official event compiler compatibility",
            "complete official scheduler/runtime equivalence",
            "native multi-control synthesis for data-record beyond the live-proven case58-shaped ordinary button-event path and the exact no-event case80 data-record+text-select plus case85 data-record+sliding-text plus case83 data-record+text-select+button oracle shapes, plus broader fixture-shaped advanced widget mixes beyond the live-proven file-browser/text-select and file-browser/sliding-text plus optional ordinary-event path",
            "live-panel proof for every supported authoring feature",
            "generic all-model TFT compiler",
        ],
    }


def editor_completion_audit() -> dict[str, Any]:
    """Return a concrete audit checklist for the independent scene->TFT->live workflow goal."""
    manifest = editor_capability_manifest()
    known_gaps = [
        "extend data-record/file-browser/file-stream advanced mixes and event semantics beyond the currently live-proven narrow shapes",
        "finish runtime semantics proof for the remaining live-negative advanced-event paths that matter to the independent workflow",
        "native multi-control synthesis for data-record beyond the live-proven case58-shaped ordinary button-event path and the exact no-event case80 data-record+text-select plus case85 data-record+sliding-text plus case83 data-record+text-select+button oracle shapes, plus broader fixture-shaped advanced widget mixes beyond the live-proven file-browser/text-select and file-browser/sliding-text plus optional ordinary-event path",
        "live-panel proof for every supported runtime feature claimed by the independent workflow",
    ]
    prompt_to_artifact_checklist = _prompt_to_artifact_checklist()
    return {
        "schema_version": 1,
        "objective": "independent scene->TFT->live runtime workflow for the current target, with official USART HMI retained only as oracle/reference tooling",
        "overall_status": "incomplete",
        "completion_gate": {
            "goal_complete": False,
            "status": "blocked",
            "reason": "The runtime-first workflow is usable for a growing supported subset, but key target-runtime boundaries are still unresolved.",
            "blocking_gaps": list(known_gaps),
        },
        "prompt_to_artifact_checklist": prompt_to_artifact_checklist,
        "criteria": [
            {
                "id": "double_clickable_desktop_editor",
                "status": "implemented",
                "evidence": [
                    "usarthmi-preview.spec",
                    "tools/usarthmi_preview_app.py",
                    "desktop EXE built from dist/usarthmi-preview.exe",
                ],
            },
            {
                "id": "project_page_authoring",
                "status": "implemented",
                "evidence": [
                    "editor capabilities group project_pages",
                    "scene new/save-as/project/pages CLI",
                    "desktop New/Save As/Project/Page/Preview Page",
                ],
            },
            {
                "id": "widget_authoring_for_current_scope",
                "status": "implemented-with-advanced-experimental-tft-boundary",
                "evidence": [
                    "widget capability registry",
                    "widgets template/templates CLI",
                    "desktop Toolbox/Properties/Object tree",
                    "scene widgets copy/cut/paste/copy-to",
                    "text-select, sliding-text, data-record, file-browser, and file-stream are direct-TFT experimental pending controls with live readback evidence",
                    "text-select/sliding-text owned down-events have COM36 runtime proof through click obj,1 raw printh markers",
                    "file-browser owned down/up events have COM36 runtime proof through click fbrowser0,1/0 raw printh markers",
                    "file-browser/file-stream may be mixed with ordinary native controls/events after COM36 proof of preserved runtime fields plus eventbtn.down markers",
                    "the narrow button.down -> fs0.val=1 case9A path is live-proven on COM36 and confirms the recovered file-stream val field mapping",
                    "the exact no-event file-stream + text-select page0 shape is now live-proven after preserving the contiguous file-stream tail descriptor payload in the mixed build path",
                    "the exact no-event file-stream + sliding-text page0 shape is now live-proven by the same contiguous tail-descriptor fix",
                    "the exact file-stream + no-event text-select + ordinary button.down marker page0 shape is also live-proven",
                    "the exact file-stream + no-event text-select + ordinary button.down -> fs0.open(t1.txt) page0 shape is also live-proven",
                    "file-browser plus no-event text-select may be mixed after case56 official compile evidence plus COM36 readback proof, and may carry optional ordinary native controls/events after COM36 button-event proof",
                    "file-browser plus no-event sliding-text may be mixed after the local case87 COM36 readback proof, may also carry an ordinary native button marker after the local case88 COM36 proof, but there is still no official same-page oracle for that pair",
                    "official GUI round2 evidence proves data-record plus an ordinary no-event button can compile and run on COM36; local native synthesis now also proves the same case58-shaped data-record page with ordinary b1.down printh",
                    "data-record/file-stream owned scene-authored events fail closed while file-browser scene-authored events are limited to owned down/up without other scene event widgets",
                    "page1 advanced controls remain fail-closed: official GUI-created minimal page1 text-select/sliding-text/data-record/file-stream cases and a separately cloned page1 file-browser case all compile positive yet return invalid_reference on the live TJC8048X543_011C panel",
                    "the exact no-event data-record plus text-select case80 oracle shape, the exact no-event data-record plus sliding-text case85 oracle shape, and the exact no-event data-record plus text-select plus ordinary button case83 oracle shape are now supported end to end; the case80/case83 locally generated HMIs also survive official GUI reopen/save, the exact aligned HMIs compile back to positive complex-page TFTs, while current-code HMI compile equivalence is still not closed and generic scene-authored data-record advanced synthesis remains guarded",
                    "the exact case85-aligned page0 shape with the existing seed button b0 patched to one down-event printh line is now public and inherits the already live-proven raw patch runtime",
                    "the exact case83 b1.down event scene is no longer blocked at build time: the public builder now uses a full-tail rebuild path that matches a fresh official-GUI-authored and official-GUI-compiled oracle byte-for-byte at 11,417,036 bytes, and a fresh COM36 live smoke now proves data0.maxval/path, select0.val, b1.txt, bar1.val, and click b1,1 -> 23 83 42 54",
                    "data-record mixed scenes beyond the case58-shaped ordinary button-event path and the exact case80/case83/case85 no-event oracle shapes, file-stream advanced mixes, and file-browser advanced mixes beyond no-event text-select/sliding-text plus optional ordinary native events remain guarded until live runtime fields are proven",
                ],
            },
            {
                "id": "canvas_layout_editing",
                "status": "implemented",
                "evidence": [
                    "scene design move/resize/align/distribute/match-size/replay",
                    "desktop canvas drag/resize/nudge/snap",
                    "desktop multi-select Align/Dist/Size controls",
                    "desktop Undo/Redo scene edit history",
                ],
            },
            {
                "id": "agent_handoff_preview",
                "status": "implemented",
                "evidence": [
                    "scene agent-preview",
                    "agent_context.json",
                    "editor_capabilities in agent context",
                    "safe_commands and hardware_policy in agent context",
                ],
            },
            {
                "id": "event_authoring_logic",
                "status": "guarded-subset",
                "evidence": [
                    "scene events list/get/set/clear/lint/graph/snippets",
                    "scene events append-command",
                    "scene events commands list/insert/replace/delete/move",
                    "scene simulate",
                    "scene scenario run",
                    "scene check --scenario",
                    "tft event-index inspect/batch",
                    "desktop Events tab contextual snippets and Save+Simulate",
                ],
                "gap": "not a complete official event compiler or scheduler/runtime proof",
            },
            {
                "id": "import_export_build_flow",
                "status": "authoring-only",
                "evidence": [
                    "hmi import",
                    "scene check",
                    "scene export",
                    "scene build",
                    "desktop Import HMI/Roundtrip HMI/Check Scene/Export Bundle/Build TFT",
                ],
                "gap": "not a byte-perfect official HMI roundtrip and not implicit hardware upload",
            },
        ],
        "known_gaps": list(known_gaps),
        "capability_manifest_status": manifest["status"],
        "hardware_policy": manifest["hardware_policy"],
        "not_claimed": manifest["not_claimed"],
    }


def _prompt_to_artifact_checklist() -> list[dict[str, Any]]:
    return [
        {
            "id": "double_clickable_exe",
            "prompt_requirement": "needs to be a clickable exe",
            "status": "implemented",
            "artifacts": [
                {"kind": "file", "path": "usarthmi-preview.spec"},
                {"kind": "file", "path": "tools/usarthmi_preview_app.py"},
                {"kind": "file", "path": "dist/usarthmi-preview.exe"},
                {"kind": "file", "path": "C:/Users/SinYu/Desktop/usarthmi-preview.exe"},
            ],
            "verification": [
                "PyInstaller build",
                "desktop exe hidden-start smoke test",
            ],
            "missing": [],
        },
        {
            "id": "official_like_authoring_surface",
            "prompt_requirement": "official USART HMI-like editor, except controls deliberately out of scope",
            "status": "implemented-with-guarded-boundaries",
            "artifacts": [
                {"kind": "command", "value": "python -m usarthmi --json editor capabilities"},
                {"kind": "command", "value": "python -m usarthmi --json widgets manifest --include-aliases"},
                {"kind": "example", "path": "examples/polished_dashboard_demo/scene.json"},
                {"kind": "example", "path": "examples/advanced_hmi_only_demo/scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/text_select_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/sliding_text_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/data_record_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_browser_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_stream_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/text_select_sliding_text_event_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/text_select_owned_event_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/sliding_text_owned_event_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/text_select_sliding_text_multi_event_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_browser_button_event_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_browser_owned_event_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_browser_text_select_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_browser_text_select_button_event_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_browser_text_select_case56_oracle_aligned_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_browser_sliding_text_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/data_record_button_event_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/data_record_text_select_case80_oracle_aligned_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/data_record_text_select_case80_current_code_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/data_record_sliding_text_case85_oracle_aligned_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/data_record_sliding_text_case85_current_code_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/data_record_text_select_button_case83_oracle_aligned_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/data_record_text_select_button_case83_current_code_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/data_record_text_select_button_case83_event_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_stream_open_case72_oracle_aligned_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_stream_open_case72_current_code_scene.json"},
                {"kind": "example", "path": "examples/advanced_direct_tft_demo/file_stream_button_event_scene.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_textselect_offline_limit_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_textselect_official_compile_negative_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_textselect_case80_oracle_aligned_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_textselect_case80_current_code_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_sltext_case85_oracle_aligned_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_sltext_case85_current_code_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_textselect_button_case83_oracle_aligned_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_textselect_button_case83_current_code_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_textselect_button_case83_event_oracle_aligned_offline_verified_2026-05-20.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_textselect_button_case83_event_live_verified_2026-05-20.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/datarecord_textselect_button_case83_event_hmi_reopen_negative_2026-05-20.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/official_hmi_roundtrip_supported_datarecord_mixes_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/current_code_datarecord_hmi_compile_status_2026-05-23.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/case80_current_hmi_compile_delta_2026-05-23.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/case83_current_hmi_compile_delta_2026-05-23.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/case85_current_hmi_compile_delta_2026-05-23.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/file_stream_open_case72_oracle_aligned_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/file_stream_open_case72_current_code_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/page1_textselect_official_gui_live_negative_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/page1_sltext_official_gui_live_negative_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/page1_datarecord_official_gui_live_negative_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/page1_filestream_official_gui_live_negative_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/file_browser_text_select_current_code_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/file_browser_sliding_text_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/case56_oracle_aligned_live_verified_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/case56_filebrowser_textselect_parity_gap_report_2026-05-19.json"},
                {"kind": "file", "path": "examples/advanced_direct_tft_demo/case56_oracle_aligned_parity_gap_report_2026-05-19.json"},
            ],
            "verification": [
                "widget capability registry covers supported and pending current-target controls",
                "scene validation and preview tests cover normal and pending widgets",
                "text-select, sliding-text, data-record, file-browser, and file-stream direct TFT outputs byte-match official GUI oracles and pass live serial readback; replay-bypassed single-control native evidence now covers data-record, file-browser, and file-stream",
                "text-select plus sliding-text can coexist with a normal button printh event and pass COM36 runtime smoke",
                "file-browser plus a normal button printh event can coexist and pass COM36 runtime smoke with fbrowser0.dir/filter preserved",
                "file-stream plus a normal button printh event can coexist and pass COM36 runtime smoke with fs0.en/val preserved",
                "the narrow button.down -> fs0.val=1 case9A scene now passes corrected COM36 runtime smoke with post-click fs0.val=1 and confirms the recovered file-stream val slot",
                "the exact no-event file-stream + text-select scene now builds through the public path, matches the repaired live probe TFT byte-for-byte, and preserves fs0.en, fs0.val, and select0.val on COM36",
                "the exact no-event file-stream + sliding-text scene now builds through the public path, matches the repaired live probe TFT byte-for-byte, and preserves fs0.en, fs0.val, and slt0.txt on COM36",
                "the exact file-stream + no-event text-select + ordinary button.down marker scene now builds through the public path, matches the repaired live probe TFT byte-for-byte, preserves fs0.en/fs0.val/select0.val/eventbtn.txt, and click eventbtn,1 emits 23 A7 42 54 23 A7 42 55 on COM36",
                "the exact file-stream + no-event text-select + ordinary button.down -> fs0.open(t1.txt) scene now passes COM36 with t1.txt=sd0/cp.bin, click b1,1 -> 23 AB 72 01 23 AB 72 02, fs0.en=1, fs0.qty=16, and select0.val still 0",
                "text-select owned down-event can emit a raw printh marker on COM36",
                "sliding-text owned down-event can emit a raw printh marker on COM36",
                "file-browser owned down/up events can emit raw printh markers on COM36 while preserving fbrowser0.dir/filter",
                "file-browser plus no-event text-select can coexist and pass COM36 runtime smoke with fbrowser0.dir/filter plus select0.val preserved",
                "the canonical no-event file-browser + text-select build now reuses the official case56 raw TFT layout with scene coordinate patching and still reads back fbrowser0.dir/filter and select0.val on COM36, while the case56-oracle-aligned scene build reproduces the official case56 TFT byte-for-byte and still passes COM36 upload/readback/camera",
                "file-browser plus no-event text-select plus an ordinary button down-event can coexist and pass COM36 runtime smoke with fbrowser0.dir/filter, select0.val, and eventbtn.txt preserved plus click eventbtn,1 marker matched",
                "file-browser plus no-event sliding-text now passes a local COM36 runtime probe with fbrowser0.dir/filter and slt0.txt preserved, and the same pair can also carry an ordinary button.down marker locally, but there is still no official same-page oracle for this pair",
                "official GUI case58 data-record plus ordinary no-event button uploaded on COM36 and preserved data0.maxval, data0.path, and b1.txt",
                "case58-shaped data-record plus ordinary b1.down printh generated locally, uploaded on COM36, preserved data0.maxval/path, b1.txt, and bar1.val, and click b1,1 emitted raw hex 23 08 44 52",
                "the exact no-event case80 data-record plus text-select scene now reproduces the official oracle byte-for-byte and passes COM36 upload/readback/camera with data0.maxval, data0.path, and select0.val",
                "the exact no-event case85 data-record plus sliding-text scene now reproduces the official oracle byte-for-byte and passes COM36 upload/readback/camera with data0.maxval, data0.path, and slt0.txt",
                    "the case85 current-code data-record plus sliding-text scene now reuses the official raw TFT layout with scene-specific coordinate patching and still passes COM36 upload/readback/camera with data0.maxval, data0.path, and slt0.txt",
                    "the exact case85-aligned page0 shape with the existing seed button b0 patched to one down-event printh line now builds through the public path, matches the live-proven raw patch byte-for-byte, and preserves data0.maxval/path plus slt0.txt while click b0,1 emits 23 B7 42 54 on COM36",
                    "the public case85 no-event data-record plus sliding-text plus ordinary button HMI-only path now compiles positively after the builder normalizes slt0 to donor geometry and promotes native named 0.pa to the active 7539-byte page, reaching donor-graft compiled TFT parity at 11,416,356 bytes / object region 0x3324",
                    "the public case85 event-bearing data-record plus sliding-text plus ordinary button HMI-only path now compiles positively after native named 0.pa promote, reaching a non-empty 11,416,372-byte / object-region 0x3334 class",
                    "the case85 new-button no-event and event direct-TFT replay paths are now oracle-aligned for the exact fixture scenes, and the first case85 event-family marker/text/geometry variations also close inside that replay family",
                    "inside the current case85 new-button event replay family, marker, text, moved-button geometry, style-only, the first style+text/style+geometry compositions, the exact same-family two-button scene, the second-button style/text/geometry/event mutations, the exact three-button scene, the third-button text/geometry mutations, and the exact third-button-event plus its first text/geometry mutations now all close; the next remaining work moves back out to wider three-button or broader multi-button/event generalization beyond these exact replay fixtures",
                    "the exact no-event case83 data-record plus text-select plus ordinary button scene now reproduces the official oracle byte-for-byte and passes COM36 upload/readback/camera with data0.maxval, data0.path, select0.val, b1.txt, and bar1.val",
                    "the exact case83 b1.down event scene now reproduces a fresh official-GUI-authored and official-GUI-compiled event oracle byte-for-byte and has fresh COM36 live proof, while a separate reopen probe still shows that a local patched event HMI is not preserved by official GUI reopen/save",
                    "the current-code case80/case83/case85 data-record HMI outputs now have explicit exact-donor compile-positive evidence: they no longer collapse to the 11,403,460-byte / object-region 0xC4 empty-shell class under official low-level compile, and case80/current plus case83/current plus case85/current now each reach the exact official compile output for their supported donor family",
                    "the current-worktree case80 current-code HMI compile delta was first narrowed to select0 geometry against the exact aligned positive page, and is now closed at the container layer: preserving the old exact donor 0.pa as a shadow entry during exact-donor rebuild restores byte-identical official compile parity for case80/current",
                    "the current-worktree case83 current-code HMI compile delta is now narrowed to select0/b1 geometry plus the b1.val field-marker byte: geometry-only restoration is still not enough, but geometry plus that marker restores the positive compile class",
                    "the current-worktree case85 current-code diagnostics now split cleanly: legacy historical-container probes still expose early shadow/tail sensitivity, while the exact-donor lane is already narrowed to the six slt0 geometry bytes because restoring those bytes alone recovers the exact case85 official compile class",
                    "the exact case72 file-stream open scene now reproduces the official fs0.open(t1.txt) oracle byte-for-byte and still passes the live open-file smoke, while the case72 current-code scene reuses the official raw TFT layout with scene text/coordinate patching and passes the same smoke",
                "text-select, sliding-text, and a normal button can coexist with three independent down-event markers on COM36",
            ],
            "missing": [
                "native multi-control synthesis for data-record beyond the live-proven case58-shaped ordinary button-event path and the exact no-event case80 data-record+text-select plus case85 data-record+sliding-text plus case83 data-record+text-select+button oracle shapes, plus broader fixture-shaped advanced widget mixes beyond the live-proven file-browser/text-select and file-browser/sliding-text plus optional ordinary-event path",
                "broader data-record compile-path recovery beyond the currently supported case80/case83/case85 current-code mixes, whose exact official compile parity is now closed in exact-donor lanes",
            ],
        },
        {
            "id": "agent_handoff",
            "prompt_requirement": "agent can inspect previews and safely intervene",
            "status": "implemented",
            "artifacts": [
                {"kind": "command", "value": "python -m usarthmi --json scene agent-preview <scene> --out-dir <dir>"},
                {"kind": "file", "path": "agent_context.json"},
                {"kind": "file", "path": "preview.annotated.png"},
                {"kind": "file", "path": "scenario.template.yaml"},
            ],
            "verification": [
                "agent_context exposes safe_commands and hardware_policy",
                "scenario template is generated from real non-empty events when available",
            ],
            "missing": [],
        },
        {
            "id": "event_logic_authoring",
            "prompt_requirement": "code logic can operate events",
            "status": "guarded-subset",
            "artifacts": [
                {"kind": "command", "value": "python -m usarthmi --json scene events append-command <scene> <event> ..."},
                {"kind": "command", "value": "python -m usarthmi --json scene events commands replace <scene> <event> --dry-run --simulate"},
                {"kind": "command", "value": "python -m usarthmi --json scene scenario run <scene> <scenario.yaml>"},
                {"kind": "command", "value": "python -m usarthmi --json scene check <scene> --simulate-events --scenario <scenario.yaml>"},
                {"kind": "command", "value": "python -m usarthmi --json tft event-index inspect --hmi <file.HMI> --tft <file.tft/run>"},
                {"kind": "command", "value": "python -m usarthmi --json tft event-index batch <case-or-hmi-path> --out <event_index_batch.json>"},
                {"kind": "script", "path": "tools/lifecycle_oracle_delta_report.py"},
                {"kind": "file", "path": "examples/event_index_batch_3841424344_2026-05-18.json"},
                {"kind": "file", "path": "examples/case51_04_second_page_load_source_events_official_event_index.json"},
                {"kind": "file", "path": "examples/case52_01_page0_load_printh_only_official_event_index.json"},
                {"kind": "file", "path": "examples/case52_02_page0_loadend_printh_only_official_event_index.json"},
                {"kind": "file", "path": "examples/case52_03_page0_load_and_loadend_printh_only_official_event_index.json"},
                {"kind": "file", "path": "examples/case52_04_page0_load_printh_long_body_official_event_index.json"},
                {"kind": "file", "path": "examples/case52_05_button_up_same_printh_payload_official_event_index.json"},
                {"kind": "file", "path": "examples/case52_06_page1_load_printh_only_official_event_index.json"},
                {"kind": "file", "path": "examples/case52_lifecycle_delta_report_20260518.json"},
                {"kind": "file", "path": "examples/case52_lifecycle_dispatch_candidates_20260518.json"},
                {"kind": "file", "path": "examples/case51_case52_lifecycle_dispatch_candidates_20260518.json"},
                {"kind": "file", "path": "reverse_usarthmi/case52_page0_load_runtime_smoke_20260518/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case52_page0_load_local_v2_smoke_20260518/smoke_result.json"},
                {"kind": "file", "path": "examples/lifecycle_runtime_smoke/page0_load_local_generated_verified_2026-05-18.json"},
                {"kind": "file", "path": "examples/lifecycle_runtime_smoke/lifecycle_runtime_equivalence_report_2026-05-19.json"},
            ],
            "verification": [
                "offline event lint, graph, command diff, simulation, and scenario reports",
                "compiled TFT event-index inspect/batch evidence reports for scheduler/index/flags review",
                "case_38/41 object-event bytecode matches official TFT event tables; case_42 data-record object-event bytecode matches official TFT tables and reports the official page-load repo candidate at 0x70B while scheduling remains unproven; case_43/44 visible file startup prefixes match at 0x2348, separate the immediate hidden 0xBF unload method call, expose following preview items for the current-path expression, if_field_ne not-empty condition, file action visibility toggles, and spstr field-slot mapping, can compile that spstr shape plus btlen, no-else if(field<field), &txt&/&id& placeholders, dp, UTF-8 current-path expression, and not-empty condition back to official payloads for the observed shapes, and now expose all_page_summary/additional_pages evidence for all eleven case43/44 2.pa main object-event byte matches with zero main-page compile errors while runtime callbacks remain unproven",
                "case51 minimal scheduler oracles locate page0 load phase 0x327, button table 0x18B / first executable 0x197, timer table 0x1C7 / first executable 0x1D4, and page1 load phase 0x45A with global_slot_offset=149 and page1.t0.txt slot 0xD2; phase descriptors now include head/tail context and show no recovered LE32 dispatch reference to page0 0x327 or page1 0x45A in the object region, while runtime dispatch remains unproven",
                "case52-01 through case52-06 official oracles are captured: page0 lifecycle phases stay at 0x2AB with no direct LE32 dispatch references, load+loadend appears as one merged phase with prefix length 47, the long load body raises prefix length to 50, same-payload button-up uses the object callback table at 0x18B / first executable 0x1A1 / slot_0x10, and the clean page1-load candidate sits at 0x255 with one prefix_end reference at 0x1AEB; lifecycle_dispatch_candidate_report shows that referenced value 0x272 is also event_table_start for primary page0/t0/bar1, and lifecycle_record_fields show page record callback slots stay 0xFFFFFFFF while event_offset_0x34 points to page event-table or wrapper boundaries, so case52-06 still has alias risk and remains compiler-oracle evidence only",
                "case52-01 official page0 load TFT was uploaded to the live panel and command-driven page 0 reload emitted raw hex AA 52 10 01, proving the page lifecycle runtime callback dispatches for the minimal page0 load shape",
                "local scene-to-TFT page0 load now emits a post_primary_page_event phase and was live-uploaded on COM36; command-driven page 0 reload emitted raw hex AA 52 10 01 and get t0.txt returned INIT",
                "lifecycle_runtime_equivalence_report_2026-05-19.json now lays out the current narrowing explicitly: official lifecycle oracles do not prove callback-slot dispatch, the local page0 positive is a narrow post-primary success, and blind page1 slot writes remain clean negative evidence",
            ],
            "missing": [
                "complete official event compiler compatibility",
                "complete official scheduler/runtime equivalence",
            ],
        },
        {
            "id": "import_export_roundtrip",
            "prompt_requirement": "open/import/export projects like the official editor",
            "status": "authoring-only",
            "artifacts": [
                {"kind": "command", "value": "python -m usarthmi --json hmi import <file.HMI> --out-dir <dir>"},
                {"kind": "command", "value": "python -m usarthmi --json hmi roundtrip-check <file.HMI> --out-dir <dir> --source-tft <official.tft/run>"},
                {"kind": "desktop", "value": "Roundtrip HMI button"},
                {"kind": "command", "value": "python -m usarthmi --json scene export <scene> --out-dir <dir>"},
                {"kind": "command", "value": "python -m usarthmi --json scene build <scene> --seed <seed.HMI> --out <dir>"},
            ],
            "verification": [
                "lossy import preserves known object geometry/properties/events",
                "roundtrip-check compares source and regenerated HMI structure and can fold in event-index scheduler blockers from an official TFT/run oracle",
                "export bundle writes preview, diagnostics, agent context, and optional guarded build outputs",
            ],
            "missing": [
                "byte-perfect official HMI project roundtrip",
                "complete resource/font reconstruction",
            ],
        },
        {
            "id": "hardware_proof",
            "prompt_requirement": "prove behavior on the current screen when claiming runtime support",
            "status": "incomplete",
            "artifacts": [
                {"kind": "command", "value": "python -m usarthmi --json tft upload --file <file.tft> --port COM36 --progress"},
                {"kind": "command", "value": "python -m usarthmi --json sendme --port COM36"},
                {"kind": "script", "path": "tools/live_case_smoke.py"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_text_select_20260518/smoke_20260518_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_sliding_text_20260518/smoke_20260518_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_data_record_20260518/smoke_20260518_readback/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_file_browser_20260518/smoke_20260518_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_file_stream_20260518/smoke_20260518_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_text_select_sliding_text_event_20260518/smoke_20260518_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_text_select_owned_event_20260518/smoke_20260518_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_sliding_text_owned_event_20260518/smoke_20260518_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_text_select_sliding_text_multi_event_20260518/smoke_20260518_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_file_browser_button_event_20260518/smoke_20260518_fixed_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_file_browser_owned_event_20260518/smoke_20260518_live_current/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_file_browser_text_select_20260518/smoke_20260518_live_current/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_file_browser_text_select_button_event_20260518/smoke_20260518_live_current/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case56_oracle_aligned_live_candidate_20260519/smoke_20260519_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case87_filebrowser_sltext_probe_20260519/smoke_20260519_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case88_filebrowser_sltext_button_event_20260519/smoke_20260519_recheck/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case80_datarecord_textselect_live_candidate_20260519/smoke_20260519_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case85_datarecord_sltext_live_candidate_20260519/smoke_20260519_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case85_datarecord_sltext_current_code_probe_20260519/smoke_20260519_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case83_datarecord_textselect_button_live_candidate_20260519/smoke_20260519_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case83_datarecord_textselect_button_current_code_probe_20260519/smoke_20260519_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case72_oracle_aligned_live_candidate_20260519/smoke_20260519_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case72_current_code_probe_20260519/smoke_20260519_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_file_stream_button_event_20260518/smoke_20260518_live_current/smoke_result.json"},
                {"kind": "file", "path": "C:/Users/SinYu/Desktop/case_for_codex/case_58_datarecord_button_event_valid_oracle_v2/smoke_20260518_official_round2_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/advanced_direct_tft_data_record_button_event_20260518_fixed/smoke_20260518_upload/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case52_page0_load_runtime_smoke_20260518/smoke_result.json"},
                {"kind": "file", "path": "reverse_usarthmi/case52_page0_load_local_v2_smoke_20260518/smoke_result.json"},
            ],
            "verification": [
                "live claims require serial readback, checksum, fixture byte comparison, or camera capture",
                "text-select, sliding-text, data-record, file-browser, and file-stream were uploaded and read back on COM36 with camera captures",
                "text-select plus sliding-text plus eventbtn.down printh uploaded on COM36 and click eventbtn,1 emitted raw hex 23 02 41 45",
                "text-select owned down-event uploaded on COM36 and click select0,1 emitted raw hex 23 02 44 31",
                "sliding-text owned down-event uploaded on COM36 and click slt0,1 emitted raw hex 23 02 53 31",
                "text-select plus sliding-text plus eventbtn multi-event TFT uploaded on COM36 and all three down-event markers matched",
                "file-browser plus eventbtn.down printh uploaded on COM36, preserved fbrowser0.dir/filter, and click eventbtn,1 emitted raw hex 23 03 45 56",
                "file-browser owned down/up event TFT matched the native probe, preserved fbrowser0.dir/filter, and click fbrowser0,1/0 emitted raw hex 23 05 46 42 / 23 05 46 55",
                "file-browser plus no-event text-select uploaded on COM36, preserved fbrowser0.dir/filter and select0.val, and captured the screen",
                "file-browser plus no-event text-select plus eventbtn.down printh uploaded on COM36, preserved fbrowser0.dir/filter, select0.val, and eventbtn.txt, and click eventbtn,1 emitted raw hex 23 06 42 54",
                "file-browser plus no-event sliding-text uploaded on COM36 and preserved fbrowser0.dir/filter plus slt0.txt",
                "file-browser plus no-event sliding-text plus eventbtn.down printh kept fbrowser0.dir/filter, slt0.txt, and eventbtn.txt alive and click eventbtn,1 emitted raw hex 23 87 42 54 on COM36",
                "file-stream plus eventbtn.down printh uploaded on COM36, preserved fs0.en/val, and click eventbtn,1 emitted raw hex 23 04 46 53",
                "the exact case72 file-stream open oracle uploaded on COM36, accepted runtime t1.txt patching, and click b1,1 emitted raw hex 23 72 00 01 23 72 00 02 with fs0.en=1 and fs0.qty=16",
                "the case72 current-code file-stream open scene reused the official raw TFT layout, then passed the same COM36 open-file smoke with t1.txt=sd0/cp.bin, click marker, fs0.en=1, and fs0.qty=16",
                "official GUI case58 data-record plus ordinary no-event button uploaded on COM36, preserved data0.maxval=1000, data0.path=\"sd0/1.data\", and b1.txt=\"newtxt\"",
                "case58-shaped data-record plus b1.down printh uploaded on COM36, preserved data0.maxval/path, b1.txt, and bar1.val, and click b1,1 emitted raw hex 23 08 44 52",
                "case80 exact no-event data-record plus text-select uploaded on COM36 and preserved data0.maxval=1000, data0.path=\"sd0/1.data\", and select0.val=0",
                "case85 exact no-event data-record plus sliding-text uploaded on COM36 and preserved data0.maxval=1000, data0.path=\"sd0/1.data\", and slt0.txt=\"000\\r\\n111\\r\\n222\\r\\n333\\r\\n444\\r\\n666\\r\\n777\\r\\n777\\r\\n888\\r\\n999\"",
                "case85 current-code data-record plus sliding-text uploaded on COM36 and preserved data0.maxval=1000, data0.path=\"sd0/1.data\", and slt0.txt=\"000\\r\\n111\\r\\n222\\r\\n333\\r\\n444\\r\\n666\\r\\n777\\r\\n777\\r\\n888\\r\\n999\"",
                "case83 exact no-event data-record plus text-select plus ordinary button uploaded on COM36 and preserved data0.maxval=1000, data0.path=\"sd0/1.data\", select0.val=0, b1.txt=\"newtxt\", and bar1.val=60",
                "case52 page0 load runtime emitted the expected raw printh marker after page reload",
                "local generated page0 load TFT emitted the expected raw printh marker after page reload and kept t0.txt readable as INIT",
            ],
            "missing": [
                "live-panel proof for every supported authoring feature",
            ],
        },
    ]
